#################################################
#################################################
###########  YAML for BCN20000 DL  ##############
#################################################
#################################################

# Model variables
model_name: 'effb0'

learning_rate: 0.00030
regularization: 0.00001

